# Generated by Django 5.0.6 on 2024-06-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(max_length=20)),
                ('accountName', models.CharField(max_length=20)),
                ('accountNumber', models.CharField(max_length=20)),
                ('ifscCode', models.CharField(max_length=20)),
                ('aadharNumber', models.CharField(max_length=20)),
                ('panNumber', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('middleName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobileNumber', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('image', models.JSONField()),
                ('presentAddresss', models.CharField(max_length=50)),
                ('permenentAddress', models.CharField(max_length=50)),
                ('copyAddress', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('months', models.CharField(max_length=20)),
                ('years', models.CharField(max_length=20)),
                ('currentLocation', models.CharField(max_length=50)),
            ],
        ),
    ]
