# Generated by Django 5.0.6 on 2024-06-21 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20240621_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentOrganizationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joiningDate', models.DateField()),
                ('appraisalDate', models.DateField()),
                ('currentCTC', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educationName', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=20)),
                ('universityName', models.CharField(max_length=20)),
                ('yearOfPassing', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('totalYear', models.CharField(max_length=20)),
                ('lastCTC', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('middleName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobileNumber', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('presentAddresss', models.CharField(max_length=50)),
                ('permenentAddress', models.CharField(max_length=50)),
                ('copyAddress', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('months', models.CharField(max_length=20)),
                ('years', models.CharField(max_length=20)),
                ('currentLocation', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PersonalDetails',
        ),
        migrations.DeleteModel(
            name='ProfessionalDetails',
        ),
        migrations.RenameModel(
            old_name='BankDetails',
            new_name='BankDetail',
        ),
        migrations.AddField(
            model_name='employee',
            name='bankDetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.bankdetail'),
        ),
        migrations.AddField(
            model_name='employee',
            name='currentOrganizationDetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.currentorganizationdetail'),
        ),
        migrations.AddField(
            model_name='educationdetails',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AddField(
            model_name='experiencedetails',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='personalDetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.personaldetail'),
        ),
        migrations.AddField(
            model_name='employee',
            name='professionalDetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.professionaldetail'),
        ),
    ]
