# Generated by Django 5.0.6 on 2024-06-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_currentorganizationdetail_educationdetails_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentorganizationdetail',
            name='appraisalDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currentorganizationdetail',
            name='joiningDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
