# Generated by Django 5.0.6 on 2024-06-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_currentorganizationdetail_appraisaldate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
