# Generated by Django 5.0.6 on 2024-07-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionaldetail',
            name='skills',
            field=models.CharField(default='', max_length=100),
        ),
    ]
