# Generated by Django 5.0.6 on 2024-07-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_professionaldetail_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetail',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
